# from https://docs.github.com/en/actions/guides/publishing-docker-images

name: Build and Push Buoy API Container
on:
  push:
    branches:
      - main
      - ci-build-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ridatadiscoverycenter/riddc-api

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo $QA_ENV_FILE | base64 --decode > .env

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
